### PR TITLE
Feature Implemented (Prevent image duplication when dragging and dropping image files in the media folder. #133)

### LINKED ISSUE #93: Adding an image seems to reencode it
HI, thanks for the extension, pretty cool.
I am wondering if images added from a local file are / have to get reencoded when being added to a note via the toolbar shortcut? This happens for me even if I add an image which is already in the .media directory (and therefore got converted already initially) a second time.

The same goes for renaming - would it be an option to keep the filename as it is?

Thanks and best regards,

Joost

### LINKED ISSUE #133: Feature Request: Prevent image duplication when dragging and dropping image files in the media folder.
When I drag and drop an image from the media folder, I want it to be assumed that I am reusing the same image.

## Current behavior (Unotes v1.4.3)
1. the media folder setting is "./img"
image

2. Drop and drop the file "./img/green1.png"
dnd1

3. Unotes duplicates the image and save as "./img/img_0.png"
4. The image link will be as follows.
dnd2

## Desired behavior
I want it to be markdown as follows.
``` markdown
![green1.png](./img/green1.png)
```
## Implementation plan
We can Implement at onPaste(e) function.
argument `e` has full path of the image file.

### PR DESCRIPTION
**Pull request by kiyoka**
Feature Implemented.
This makes local file handling more convenient.

**Unotes version:**
1.4.3

## Description
- Fixes #133
- Fixes #93
- Dragging and dropping images in the media folder does not duplicate the images.
- Selecting an image in the media folder from the toolbar does not duplicate the image.
- Image files under the media folder are not duplicated even in deep hierarchies.
- Supported Windows style path and Windows style separator '\\'.
- Supported Windows drive letters.

## Tested
- Tested only on Windows 10 Pro.
- Tested with and without drive letter in path.
- Tested the case where the media folder setting is a relative path.
- Tested the case where the media folder setting is an absolute path.

## Not tested
- Not tested on macOS.
- Not tested on Linux.

If you have one of these unix path style environments, please check that it works.

### CODE REVIEW

**Comment by ryanmcalister** [comment]
Looks good. Just ran into one issue testing on Linux.

**Comment by kiyoka** [comment]
What kind of issue is it?
Let me know and I will fix it.
I will also be installing an Ubuntu 22 environment.

**Comment by ryanmcalister** [comment]
> What kind of issue is it? Let me know and I will fix it. I will also be installing an Ubuntu 22 environment.

Sorry, I forgot to finish submitting the review. See the comments in the code review.

**Comment by kiyoka** [comment]
@ryanmcalister 
Fixed path handling bug.
Please review again.

**Review by ryanmcalister — APPROVED** [review]

**Pull request merged**
